### ISSUE TITLE
Deprecate the scope switcher/scoped visibility logic and plan an alternative

### ISSUE THREAD

**Issue by ptgott** [gravitational/docs#102]
Users often don't realize that there is a scope selector, and even if they do, it's not obvious that the scope selector only exists to change the visibility of specific UI components, rather than entire docs pages, navigation sidebar links, etc. The proportion of users who navigate to a page with the `scope` query parameter versus the default scope is very small. 

At the same time, critical UI components in the docs rely on the user to select the appropriate scope, including `Admonition`s, `ScopedBlock`s, and `Details` boxes. This means that most docs readers are probably missing important information.

One possibility for fixing this is to make it clearer that parts of a given docs page are hidden due to scope, which I've proposed in #88. Another possibility is to stop using the `scope` parameter and scope switcher altogether, so all elements are visible all the time, regardless of the edition the user is using. Removing the scope switcher means that we don't need to get users acquainted with unfamiliar dynamic behavior before they can follow our docs.

If we go with this approach, we'll need to come up with a standard way to convey the same information for users of different Teleport editions. Here are some methods we've used:

|Method|Example|Issues within this method|
|---|---|---|
|Indicating differences within the same paragraph| "If you are using Teleport Cloud, set `--proxy` to the address of your tenant. If you are using a self-hosted version, set `--proxy` to the address of the Auth Service"| This makes it difficult for users to  travel linearly through the page and follow steps quickly. It can make paragraphs more convoluted than they need to be.|
|Using `Tabs`|One `TabItem` for a file configuration and one `TabItem` for a dynamic configuration method|Sometimes we need to include a `Tabs` component that applies to one edition but not another. For example, Cloud users can only use dynamic configuration resources to apply settings via CLI, but users of self-hosted editions can use static files or dynamic resources. To prevent the reader of a tutorial from completing the same step twice, it would make sense to include the self-hosted instructions in a `Tabs` component. However, this would be awkward if we're already using `Tabs` to separate instructions for different scopes.<br><br>One alternative would be to use the new dropdown menu UI to include separate instructions for Cloud/self-hosted deployments, then within one dropdown option, include individual `Tabs`.<br><br>Another difficulty with using `Tabs` is that some differences between editions, such as the endpoint to use for logging in to the cluster, are very small, and shouldn't require a `Tabs` box.|
|Edition-specific `Notice`s and `Admonition`s that are visible for all users|An `Admonition` saying, "If you are using Teleport Cloud, you must use dynamic resources"|If these are visible for all scopes, they can become distracting for users they don't apply to. Navigating a docs page becomes like a Choose your Own Adventure novel, where readers need to follow branches in addition to maintaining their attention to the step-by-step flow.|
|One page, one edition|One page for adding a Node for self-hosted editions of Teleport, with a separate page for Teleport Cloud|While there are some substantial differences between setting up Teleport in different editions, the overall flow is the same: launching the Auth/Proxy Service (including starting a Cloud account); setting up SSO and RBAC; adding resources; and carrying out repeated admin tasks like upgrades. If we have a separate page for each edition, we risk making it unnecessarily difficult to navigate the docs.|

We can come up with some clean ways to represent edition-specific information, then deprecate the scope switcher.

CC @klizhentas

**Comment by klizhentas** [comment]
I am leaning towards one page-one edition, with some sections of documentation that are common for all editions, like resources and configuration.

We can rely heavily on includes to avoid writing the same content over and over. But I need to think a bit more on the layout.

If the documentation is similar enough, we can get away with one page covering multiple editions.

**Comment by klizhentas** [comment]
I think we found a good solution. Our scope selector is per article and only shows available options, but always renders the page. @ptgott is it good to close for now?

**Comment by ptgott** [comment]
Works for me!
