### ISSUE TITLE
Add scopes for each page

### ISSUE THREAD

**Issue by klizhentas** [gravitational/docs#105]
We have removed documentation global scope switcher[ in this PR.](https://github.com/gravitational/docs/pull/94).

Global scope switcher created a lot of confusion, because it has been changing navigation and content in some unpredictable ways.

Instead of global scope, all articles are visible all the time, but clearly show what edition of the software they are designed for.

1. To add specific scopes to a page, in the navigation, you need to add a field `"forScopes"` in `/config.json` in the page object. 
```
{
  "title": "Adopters",
  "slug": "/adopters/",
  "forScopes": "enterprise, cloud"
}
```

This field takes values `oss`, `enterprise`, `cloud`. The values can be passed both as an array `["oss", "enterprise"]` or as a string `"oss, enterprise"`.

**Comment by ptgott** [comment]
Closing as completed. The `forScopes` configuration defaults to showing all scopes, and we have been editing this as we introduce new docs pages.
