### ISSUE TITLE
Indented command output in `code` block is not rendered correctly

### ISSUE THREAD

**Issue by hugoShaka** [gravitational/docs#120]
In `code` block, output is prefixed by `#`. All white-spaces between `#` and the first non-blank character are trimmed, this mangles indented output like YAML.

Repro code:

```
`` `code
$ kubectl get teleportusers myuser -o yaml
# apiVersion: resources.teleport.dev/v2
# kind: TeleportUser
# # [...]
# status:
#   conditions:
#   - lastTransitionTime: "2022-07-25T16:15:52Z"
#     message: Teleport resource has the Kubernetes origin label.
#     reason: OriginLabelMatching
#     status: "True"
#     type: TeleportResourceOwned
#   - lastTransitionTime: "2022-07-25T17:08:58Z"
#     message: 'Teleport returned the error: role my-non-existing-role is not found'
#     reason: TeleportError
#     status: "False"
#     type: SuccessfullyReconciled
`` `
```
Output:

![image](https://user-images.githubusercontent.com/16366487/181349517-2e90536a-d101-43df-88c2-e4ad8f583b47.png)

**Comment by alexfornuto** [comment]
`#` is not required to differentiate output, all lines that don't start with `$` or have a `\` ending the proceeding line are treated as output. Without the `#`:

````
```code
$ kubectl get teleportusers myuser -o yaml
 apiVersion: resources.teleport.dev/v2
 kind: TeleportUser
 # [...]
 status:
   conditions:
   - lastTransitionTime: "2022-07-25T16:15:52Z"
     message: Teleport resource has the Kubernetes origin label.
     reason: OriginLabelMatching
     status: "True"
     type: TeleportResourceOwned
   - lastTransitionTime: "2022-07-25T17:08:58Z"
     message: 'Teleport returned the error: role my-non-existing-role is not found'
     reason: TeleportError
     status: "False"
     type: SuccessfullyReconciled
```
````

![image](https://github.com/gravitational/docs/assets/2349184/876a5bbc-423a-4781-954f-09a716b4640f)

Our [UI Reference](https://goteleport.com/docs/contributing/documentation/reference/#code-blocks) documents output as unmarked and comments as marked with `#`. With all this in mind, @hugoShaka can we close this without action?
