### ISSUE TITLE
Example terminal output copied along with commands in `code` snippets

### ISSUE THREAD

**Issue by ptgott** [gravitational/docs#121]
If you create a code snippet like this...

````
```code
$ tctl create -f editor-request-rbac.yaml
role 'editor-reviewer' has been created
role 'editor-requester' has been created
```
````

...then click the full-snippet copy button, the pasted output includes the example terminal output, not just the command. I would expect the copy button to copy only the command, since users following a tutorial would want to copy commands for pasting into their own terminals.

**Comment by alexfornuto** [comment]
We may also want to consider not including the full-snippet copy button on `code` type blocks, unless we instead make a commitment in our style guide to put single multi-line commands in unique code blocks.
