### ISSUE TITLE
Teleport Architecture Overview is too low in search results for "architecture"

### ISSUE THREAD

**Issue by ravicious** [gravitational/docs#130]
It's the sixth result at the moment, behind results such as the architecture of Machine ID or Database Access. I'd expect it to be above those pages.

![search results for architecture](https://user-images.githubusercontent.com/27113/185177687-37628d6f-a635-41a8-9aec-d250b1d6b1dc.png)

**Comment by greedy52** [comment]
Similar experience today when I searched "Redshift", where the second result is the preferred one.

<img width="503" alt="Screen Shot 2022-09-14 at 9 05 00 AM" src="https://user-images.githubusercontent.com/12417665/190162296-21ab72f8-9926-4bbf-a687-914564f1b5e4.png">

The IAM reference page (the first result) is indeed a reference page for "advanced" users or use cases. The guide ideally should have higher priority.

**Comment by ptgott** [comment]
Closing so we can track search-related issues in #74
