### ISSUE TITLE
Add Mermaid support for diagrams

### ISSUE THREAD

**Issue by ptgott** [gravitational/docs#139]
I.e., as with GitHub, you could add a `mermaid` code fence with a diagram definition to an MDX file within a docs page and our docs engine would render it as a diagram using Mermaid.

Advantages over our current approach (LucidChart):

- We could build a custom theme into the docs engine, meaning that we could enforce the "art direction" of our diagrams easily, and external contributors wouldn't need to access to a LucidChart library
- More transparent version control of diagrams
- Well-composed diagrams (as long as you get familiar with the Mermaid configuration syntax)

If we adopt this approach, we could introduce Mermaid-based diagrams whenever we need a new diagram, and replace our existing diagrams gradually.

**Comment by alexfornuto** [comment]
https://github.com/gravitational/teleport/pull/8020 is a good example of where Mermaid would be a bit help for maintaining graphs.

**Comment by ptgott** [comment]
While we merged the PR that added Mermaid support (https://github.com/gravitational/docs/pull/224), the branch that adds our first rendered Mermaid charts to `gravitational/teleport` (https://github.com/gravitational/teleport/pull/23458) won't build because the GitHub Actions runner can't find Chromium.
