### ISSUE TITLE
Anchor links are broken when anchor name is a valid scope

### ISSUE THREAD

**Issue by hugoShaka** [gravitational/docs#143]
The `teleport-cluster` Helm chart has an `enterprise` setting and its reference has an enterprise section.

When opening a link that points to this section the browser scrolls top instead of scrolling down to the relevant section. This is frustrating as trying to open the section in the side toc panel will scroll up instead of showing the correct piece piece of doc.

Example: https://goteleport.com/docs/reference/helm-reference/teleport-cluster/?scope=enterprise#enterprise

This is caused by the section and button ids conflicting:
* anchor name is generated from the section title slug
* section title is `#enterprise`
* radio button for the entreprise scope button also has id="enterprise"
* browser takes the first id match and scrolls top

**Comment by alexfornuto** [comment]
A possible solution may be to have the transformer check for existing anchors and iterate (-1) when found.

**Comment by ptgott** [comment]
Closing as no longer an issue since the docs engine no longer navigates based on the `scope` query key
