### ISSUE TITLE
Update Helm Deployment Guides page

### ISSUE THREAD

**Issue by scottpgallagher** [gravitational/docs#149]
On the following page (https://goteleport.com/docs/deploy-a-cluster/helm-deployments/?scope=enterprise) the information on the right hand side doens't line up with what is on the submenu to the left. All the items from the left submenu should be included on the right page as it's often overlooked by prospects/customers looking to just deploy a standalone Teleport installation in Kubernetes.

**Comment by ptgott** [comment]
@scottpgallagher Is there a more general way to describe this issue that applies to docs pages besides the Helm Deployments menu page?

**Comment by ptgott** [comment]
This is a content issue, rather than a docs engine issue, so I am going to close it here and open a similar issue in `gravitational/teleport`.
