### ISSUE TITLE
Pages with no `forScopes` setting don't show scope switcher buttons

### ISSUE THREAD

**Issue by ptgott** [gravitational/docs#159]
Sometimes, a page applies to the `oss`, `cloud`, and `enterprise` scopes, but still has information specific to each scope, where it's important to include the scope switcher buttons at the top of the page.

However, for pages in `gravitational/teleport` with no `forScopes` configuration in `docs/config.json`, no scope switcher buttons appear.

We should change the behavior of the scope switcher buttons to render all three scope possibilities when a page has no `forScopes` setting.

**Comment by alexfornuto** [comment]
This has been resolved, likely during the MDX-hast upgrades.
