### ISSUE TITLE
Highlight temp values in example code blocks

### ISSUE THREAD

**Issue by alexfornuto** [gravitational/docs#163]
DigitalOcean shows a different highlight for items that need to be updated by users. I've 
<img width="428" alt="image" src="https://user-images.githubusercontent.com/559288/187245604-5f83d689-bbfe-4dbd-9e51-dce6650f6bf2.png">
 
I ran into the same problem with Ansible Docs, as there is no visual clue that it needs to be updated. 
<img width="560" alt="image" src="https://user-images.githubusercontent.com/559288/187245938-b4a59dd0-e843-428b-bd42-9e6a494180fb.png">

_Originally posted by @benarent in https://github.com/gravitational/teleport/issues/15907#issuecomment-1230528310_

The [ask] is to add the ability to the docs stack to highlight specific sections of code blocks. PrismJS can [highlight lines](https://prismjs.com/plugins/line-highlight/) with a plugin, but I'm not sure how we'd do it for individual blocks of text. In any case, I'll split this into a feature request for the docs repo.

**Comment by ptgott** [comment]
Closing since we can use the `Var` component for this in syntax-highlighted code snippets.
