### ISSUE TITLE
Version labels in collapsable header looks like a tab

### ISSUE THREAD

**Issue by hatched** [gravitational/docs#166]
The `OSS` and `Enterprise` labels in the headers here look like they are tabs.

https://goteleport.com/docs/access-controls/sso/azuread/?scope=enterprise#make-sure-you-can-connect-to-teleport

### Current States
Normal:
<img width="501" alt="Screen Shot 2022-10-17 at 11 41 45 AM" src="https://user-images.githubusercontent.com/532033/196246041-bc3be9f1-8181-453b-bde1-20602897b565.png">

Hovered:
<img width="516" alt="Screen Shot 2022-10-17 at 11 39 46 AM" src="https://user-images.githubusercontent.com/532033/196245914-98be8041-bd55-43d8-beef-5f428a05c86b.png">

Collapsed:
<img width="494" alt="Screen Shot 2022-10-17 at 11 41 59 AM" src="https://user-images.githubusercontent.com/532033/196246045-0860e6de-cee7-496e-b65a-bbee6d9727ed.png">

### Fix
A possible fix would be to invert the label background when it's not collapsed:
<img width="479" alt="Screen Shot 2022-10-17 at 11 46 08 AM" src="https://user-images.githubusercontent.com/532033/196246784-e45ddf59-754e-4544-9742-f680190150a6.png">

**Comment by ptgott** [comment]
Closing since we're using Docusaurus-native details boxes in the new site, and these don't include edition labels.
