### ISSUE TITLE
Icon Parity with Product

### ISSUE THREAD

**Issue by alexfornuto** [gravitational/docs#183]
Thanks to #177 we can now use an Icon component to insert inline icons into docs copy. This helps us better document product features that use Icons as part of their title/header/reference.

The ask here is to update (and ideally synchronize for future-proofing) this projects [icons](https://github.com/gravitational/docs/tree/main/components/Icon/svg) with those used in our Web UI and Teleport Connect.

While attempting to document the Icon component I discovered at least two missing icons, the bell used for "Activity" and the terminal used for "Active Sessions".

**Comment by ptgott** [comment]
Closing since the `Icon` component is not being ported to the new Docusaurus site.
