### ISSUE TITLE
Provide Vars component to more than "code" code blocks.

### ISSUE THREAD

**Issue by alexfornuto** [gravitational/docs#186]
Currently the `<Var>` component is only usable in code blocks if:

- The code block is using the `code` syntax,
- The line where it's called is a "command" line (begins with `$`.

While I understand the logic that went into that decision, this component could be much more useful if it were allowed to render on all lines of all code blocks. Starting with the second point above, one may want to use the same content of a <Var> in the output of a command so that it matches what's expected based on input.

More generally, this component could be used to improve the example config snippets we provide in `yaml` and similarly highlighted code blocks. A prime example (the one that led me here) would be a Var for the Teleport Auth/Proxy server address. Adding this and other key vars relevant to the specific doc could make for config examples that readers can just drag, drop, and go with.

**Comment by alexfornuto** [comment]
Update: The Var component in code blocks only renders in the command itself, not in the output. This detracts from our ability to use this component in cases where the displayed output of a command is dependent on the value of the Var. See [#26636](https://github.com/gravitational/teleport/pull/26636) for an example.

**Comment by webvictim** [comment]
To follow on from this, it would also be nice if the var had more code-like formatting when used in code blocks - at the moment they display in a much larger font than the surrounding code.

**Comment by ninaTorgunakova** [comment]
As the solution was merged, I returned Vars to the code output on the Register Cluster page that was deleted in https://github.com/gravitational/teleport/pull/26636, I opened PRs in the `gravitational/teleport` repo.

**Comment by ninaTorgunakova** [comment]
@alexfornuto seems this issue can be closed after merging returned vars on the Register Cluster page to versions [12](https://github.com/gravitational/teleport/pull/27925) and [13](https://github.com/gravitational/teleport/pull/27926) (already merged for the [14](https://github.com/gravitational/teleport/pull/27927))

**Comment by alexfornuto** [comment]
Currently we can apply Var blocks to more code blocks than `code`, syntax highlighting is lost. This is something we'll want to resolve, so rather than create a new issue how about we leave this one open until we can use Var blocks and syntax highlighting in the same block?
