### ISSUE TITLE
Improve the discoverability of the docs scope switcher

### ISSUE THREAD

**Issue by ptgott** [gravitational/docs#20]
Currently, the docs site includes a scope switcher that we use to adjust the visibility of certain components as well as the navigation side menu. This sits next to the version switcher.

<img width="418" alt="image" src="https://user-images.githubusercontent.com/25250668/160694359-f6a59571-1de3-48c2-8ce6-4a396bee96e7.png">

The current UX can be more discoverable:
- The version picker redirects a user to the docs home page, rather than the counterpart of the current page in the chosen version.
- The scope switcher has multiple options, and these options dictate the visible content of the site. Since "OpenSource" is the default, if a user does not adjust the value of the scope switcher, any content relevant only to Cloud or Enterprise deployments will be invisible. It would be great if users were encouraged or invited to pick the most relevant scope as early as possible during their time on the site.

Other changes we should make:
- Make the scope switcher higher in the hierarchy of components that a user would see when visiting a docs page
- Remove all unsupported Teleport versions from the version switcher
- Change the visible text of the scope switcher options to "Open Source", "Enterprise Cloud" and "Enterprise On-Premises" (or similar)

Thanks for your help with this!

**Comment by Alqanar** [comment]
Created a task https://app.asana.com/0/1201950389251748/1202072636317394
