### ISSUE TITLE
Consider supporting mermaid in our docs

### ISSUE THREAD

**Issue by klizhentas** [gravitational/docs#207]
https://github.com/vercel/next.js/discussions/12837

[Mermaid](https://mermaid-js.github.io/mermaid/#/) de-facto took over our RFD and our docs team loves it. Would be good to add support for it, and style it in a way that matches our existing lucidchart diagrams:

https://goteleport.com/docs/architecture/authorization/#external-users-from-sso-providers

Although it will never reach the level of custom diagrams, it is a super handy tool to generate simple flows / charts on the fly and embed those.

**Comment by alexfornuto** [comment]
Possible duplicate of #139

**Comment by ptgott** [comment]
Closing since we have decided to support Mermaid. Tracking implementation hiccups in #139
