### ISSUE TITLE
Docs search displays empty results if you press "Enter" too quickly

### ISSUE THREAD

**Issue by ptgott** [gravitational/docs#229]
You must wait for a menu of results to render below the search box before pressing "Enter" takes you to a populated results page.

**Comment by alexfornuto** [comment]
@hatched @avatus Would either of you be willing/able to look at this issue with the docs team? We'd need actual devs on this one, and would like to do it right (build a test, etc).

**Comment by avatus** [comment]
Sure, assign to me

**Comment by ptgott** [comment]
Now that we have reworked the docs search around Inkeep, we can close this as completed.
