### ISSUE TITLE
Linter doesn't catch broken relative links. 

### ISSUE THREAD

**Issue by alexfornuto** [gravitational/docs#231]
https://github.com/gravitational/teleport/pull/21161 Introduced broken links relative to the partial location, but not the location the partials were used in. The linter did not catch this, and allowed broken links into production.

**Comment by ptgott** [comment]
Okay, so it looks like running this command in a `gravitational/docs` clone after running `yarn git-update` causes linter errors to appear again:

```bash
$ find content -name "package.json" -delete
```

It looks like the `remark` CLI is getting confused by one of the `package.json` files in each content directory, though I'm not sure why yet or how to overcome this.

**Comment by ptgott** [comment]
This command seems to work, I guess because it stops `remark` from searching `package.json` files for its config: `npx remark --rc-path .remarkrc.mjs <files>`
