### ISSUE TITLE
Support links to the current docs version at `/ver/<version>`

### ISSUE THREAD

**Issue by ptgott** [gravitational/docs#243]
Currently, the docs engine redirects a visitor to the 404 page if they attempt to visit a URL at the current version of the docs site, e.g., `/ver/12.x` for v12. However, this means that if we link to a future version of the docs using a `/ver/` path, the link will start to return 404s to users when that version becomes the default version of the docs.

Let's allow users to visit the current version of the docs at the `/ver/<ver>` URL path.

**Comment by alexfornuto** [comment]
Was this always the case, or did versioned paths work for the current version before #225 ?

**Comment by ptgott** [comment]
Confirming that you can now navigate directly to a docs page at a specific version.
