### ISSUE TITLE
Live Refresh is broken in dev environments.

### ISSUE THREAD

**Issue by alexfornuto** [gravitational/docs#247]
Since #225 was merged, live refresh has not worked when running `yarn dev`. Manual refresh either, I've found that only killing and restarting the process shows changes.

**Comment by ptgott** [comment]
Manual refresh has been working since #253, but it would be nice to see if live refresh can work as well.

**Comment by ptgott** [comment]
Closing as complete in the new Docusaurus site (`gravitational/docs-website`)

**Comment by alexfornuto** [comment]
So y'all switched to Docusaurus? Good idea, much easier than what y'all were using when I was there. Good on ya 👍
