### ISSUE TITLE
Videos not autoplaying

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/docs#248]
Videos are not autoplaying as muted.  The controls also don't show a user can't select to play them.

Example:
https://goteleport.com/docs/database-access/introduction/

<img width="757" alt="image" src="https://user-images.githubusercontent.com/60704961/222935516-a4101f80-a5db-4cd6-b8cd-47c1060c884a.png">

**Comment by ptgott** [comment]
We recently merged a major re-architecting of the docs site (https://github.com/gravitational/docs/pull/225), so we should investigate whether that changed the way the docs site renders video.

**Comment by alexfornuto** [comment]
I tested locally and it looks like #225 is indeed where this behavior began.

**Comment by benarent** [comment]
This issue looks resolved, tested on https://goteleport.com/docs/database-access/introduction/ and it's working.
