### ISSUE TITLE
copy/paste of code includes $

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/docs#25]
The copy option for `code`, `bash` does not exclude the `$` portion. This causes failures when attempting to use the copy option and paste. 

Example

![image](https://user-images.githubusercontent.com/60704961/161363918-22cb70fd-7ee7-4bd5-84f1-0cb2bf31f145.png)

will paste as this and fails to run properly:

```bash
# Download Teleport's PGP public key
$ sudo curl https://deb.releases.teleport.dev/teleport-pubkey.asc \
  -o /usr/share/keyrings/teleport-archive-keyring.asc
# Add the Teleport APT repository
$ cat<<EOF>/etc/apt/sources.list.d/teleport.list
deb [signed-by=/usr/share/keyrings/teleport-archive-keyring.asc] https://deb.releases.teleport.dev/ stable main
EOF
$ sudo apt-get update
$ sudo apt-get install teleport

```

**Comment by stevenGravy** [comment]
This looks like includes may be acting different on copy/paste vs `code` elements on the page.

**Comment by Alqanar** [comment]
Created a task https://app.asana.com/0/1201950389251748/1202072636317385

**Comment by C-STYR** [comment]
@stevenGravy for future tickets, please create in [Asana](https://app.asana.com/0/1201922182803749/board).  Instructions are [here](https://gravitational.slab.com/posts/creating-a-development-request-in-asana-58nzjw4u).
