### ISSUE TITLE
Add lint check for multiple newlines.

### ISSUE THREAD

**Issue by alexfornuto** [gravitational/docs#266]
> It might be good to enable this plugin in our remark config so we can keep things this way: https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-no-consecutive-blank-lines

_Originally posted by @ptgott in https://github.com/gravitational/teleport/issues/24247#issuecomment-1499645878_

**Comment by ptgott** [comment]
Closing since we have removed formatting linters that don't affect the rendered page. See #508
