### ISSUE TITLE
Version is stuck on v13.x for cloud scope, cloud is still on 12.x

### ISSUE THREAD

**Issue by nklaassen** [gravitational/docs#302]
<img width="134" alt="Screenshot 2023-05-25 at 3 29 24 PM" src="https://github.com/gravitational/docs/assets/16807901/451159ec-6ca1-4d80-9340-03a03f2aa9f4">

The version dropdown is pinned to 13.x when viewing a page with the cloud scope selected, but cloud is still running 12.x and seemingly won't be updated to 13.x until June 5 https://goteleport.com/docs/upcoming-releases/. It seems this was updated too early. I'm not sure where in the source this is configured.

**Comment by ptgott** [comment]
Here's where we configure the `disabled` setting for the version switcher: https://github.com/gravitational/docs/blob/ddb577dfa97a723fc1ecdad8fd595a0a4ae8c8c3/layouts/DocsPage/Header.tsx#L50-L61

This always sets the default version to `latest`. We can change this to use a pre-configured value (as @alexfornuto suggested) if the scope is `cloud` or `team`.

**Comment by ptgott** [comment]
Closing since we removed the scope selector.
