### ISSUE TITLE
The Improve button scrolls to the bottom of docs, but there is nothing there

### ISSUE THREAD

**Issue by ravicious** [gravitational/docs#324]
## Applies To

* https://goteleport.com/docs/architecture/authorization/

## Details

AFAIR it used to scroll to a ribbon or something that led you to the corresponding file on GitHub, but it looks like it's gone now.

## How will we know this is resolved?

The Improve button should navigate you towards the file on GitHub.

**Comment by alexfornuto** [comment]
I believe it scrolls down to put the "Was this page helpful?" feedback section in front of the reader.

**Comment by stevenGravy** [comment]
> I believe it scrolls down to put the "Was this page helpful?" feedback section in front of the reader.

Perhaps change this to provide feedback.

**Comment by dumez-k** [comment]
@alexfornuto correct, that's the idea but if it's hard for users to see we can highlight it somehow to make it more obvious on button click.  Or/and like @stevenGravy suggested, change the button text to "provide feedback"

**Comment by ravicious** [comment]
Was it ever navigating you to GitHub or am I just making this up? If it did, then I think I appreciated this feature, especially when I just joined Teleport and didn't know where to find the relevant markdown file.

**Comment by stevenGravy** [comment]
> Was it ever navigating you to GitHub or am I just making this up? If it did, then I think I appreciated this feature, especially when I just joined Teleport and didn't know where to find the relevant markdown file.

it did. We did get a lot of empty GH requests.

**Comment by dumez-k** [comment]
@ravicious there's still the option to open an issue after clicking the thumbs up thumbs down button.

<img width="499" alt="Screenshot 2023-06-22 at 8 14 55 AM" src="https://github.com/gravitational/docs/assets/41009873/0eb1dbdc-33f4-44a6-a588-9c16110d493c">

**Comment by ptgott** [comment]
Closed as complete/no longer an issue.
