### ISSUE TITLE
Add macOS Touch ID Troubleshooting Step

### ISSUE THREAD

**Issue by travelton** [gravitational/docs#395]
https://goteleport.com/docs/access-controls/guides/passwordless/#touch-id-not-usable

When running `tsh mfa add`, and you are stuck at `Tap any *registered* security key`. Be sure MFA via OTP is set up through the Teleport web interface, then add the `--mfa-mode=otp` flag... `tsh mfa add --mfa-mode=otp`.

**Comment by ptgott** [comment]
Moving to: https://github.com/gravitational/teleport/issues/32051
