### ISSUE TITLE
Docs search returns unexpected results

### ISSUE THREAD

**Issue by klizhentas** [gravitational/docs#74]
You kinda can find the tctl db ls info if you do a search for tsh - it shows up a few entries down under tsh db ls and on that page you actually see the tctl db ls entry.
no ability to phrase searches - “tctl db ls” (maybe cause search logic already assumes to search the whole phrase)

**Comment by Valien** [comment]
Another example of the lack of finding specific information:

Trying to find the hardware requirements for Teleport (what EC2 size, recommendations, etc). Searching for "hardware requirements", "ec2 size",  "requirement", "m4", etc will return nothing valid.

The actual info (for scaling) is here: https://goteleport.com/docs/setup/operations/scaling/ - but none of the keywords help with finding the data.

**Comment by alexfornuto** [comment]
If you don't mind, I'm going to co-opt this issue and broaden the scope a bit, as follows:

We need to review a few things about our Algolia Search configuration. Specifically:

- Search Bar Behavior: Sometimes when users type a query and hit `Enter` quickly, they get a blank search page. Maybe we can tweak the javascript to base the input on the separate page to accept whatever is in the field, and not what's been returned by the laggy live results.
- keywords. This speaks to the examples provided above. Ideally we should have a frontmatter key for keywords, which should be turned into html meta tags on render. Algolia should prioritize in order:
  - meta keywords
  - H2 and H3 values
  - Remaining content in the body.

To that last point, the main content of each doc should be wrapped in `<article>` tags to improve SEO globally. I'm including this here in case we can quickly/easily add this while poking at search. If not, we can spin up a separate issue for it.

**Comment by alexfornuto** [comment]
Pushing back to Q2

**Comment by ptgott** [comment]
A search solution is being implemented via Inkeep.
