### ISSUE TITLE
Create article scope

### ISSUE THREAD

**Issue by klizhentas** [gravitational/docs#85]
## Problem

We have tried multiple approaches to fix tailor navigation structure, including changing navigation in different scopes. This has proved to be confusing, because people have to constantly switch back and forth between scopes just to see the article.

Hiding navigation items or changing structure is bad for search indexing and discovery. 

Instead we should keep the navigation structure static, but have a very explicit label in the top header area that highlights the n, please create a `scopes` part in the header that works like Gitlab:

```
---
title: Application Access Role-Based Access Control
description: Role-Based Access Control (RBAC) for Teleport Application Access.
scopes: oss, enterprise, cloud
---
```

<img width="456" alt="Screen Shot 2022-07-03 at 4 24 44 PM" src="https://user-images.githubusercontent.com/13717/177060713-641d841f-546a-4459-b80c-c184798f583a.png">

Here is how title should look like approximately:

<img width="1158" alt="Screen Shot 2022-07-03 at 4 27 33 PM" src="https://user-images.githubusercontent.com/13717/177060930-bf696be9-057d-4412-a579-b8c40a44d71c.png">

Supported scope and description:

```
scope: oss, enterprise
The title should render on-hover "Available in OSS and Enterprise editions"
```

Special case is `all`, renders as: **ALL**

```
scope: all
The title should render on-hover "Available in OSS, Enterprise, Cloud editions"
```

**Comment by ptgott** [comment]
I think this would be great, and have some thoughts:

1. I think we should also indicate in the navigation sidebar that a page only applies to a particular edition. This way, a user won't need to navigate to a page to realize that it doesn't apply to their use-case. One way we could do this is below (just to illustrate what I mean). This will reduce the space we have in the nav bar for text, so we can think of alternatives as well.

<img width="244" alt="Screen Shot 2022-07-05 at 10 10 25 AM" src="https://user-images.githubusercontent.com/25250668/177348493-97ace8e4-ffe9-494b-b0b4-16ede25cae0a.png">

2. The banner indicating which edition a page supports should be as clear as possible, since some users may be arriving at the docs site without knowing that we have three editions. The majority of users already ignore the scope dropdown menu, so we should minimize the risk that users ignore this banner as well.

**Comment by klizhentas** [comment]
@ptgott we can try this, but because there are a lot of nav sections like that, we should make it more subtle, a small gray label will be better.

**Comment by ulysseskan** [comment]
[Banner blindness](https://en.wikipedia.org/wiki/Banner_blindness) may be keeping people from looking at our header and missing the edition selector on top.

To increase visibility, how about listing all sections for all editions neatly in the left navbar (perhaps also increasing contrast and making the sidebar wider), but adding bold text ""This feature is only available in the **Enterprise edition**." as a one-line 2nd paragraph of the article near the top of the page - in the **same font** as the article.

**Comment by klizhentas** [comment]
<img width="1274" alt="Screen Shot 2022-07-05 at 11 06 22 AM" src="https://user-images.githubusercontent.com/13717/177389082-ca153589-f800-4a29-88b5-139ff34ddceb.png">

@ulysseskan good point. I think we can try a simple solution to this problem by making a header to be a more regular header. @Alqanar  can you try the style above to see if it works better.

**Comment by Alqanar** [comment]
@klizhentas I would like to clarify.

1. What version of the header do we make?

- header with the grey gradient:
<img width="1653" alt="gradient_header" src="https://user-images.githubusercontent.com/41822696/177577071-cf9f69c2-3d92-479e-a19c-cf7e1b5aa798.png">

- header with the white gradient:
<img width="1655" alt="white_header" src="https://user-images.githubusercontent.com/41822696/177577291-7a363b9b-bd30-4331-9232-7762f57b51c7.png">

- header with extra line, where we specify scope
<img width="1652" alt="header_with_extra_line" src="https://user-images.githubusercontent.com/41822696/177577539-5a706bef-052d-4e51-9bf1-2ad5726bcbd1.png">

2. Do we make any changes to the navigation? Something like that?
<img width="312" alt="Screenshot 2022-07-06 at 17 39 04" src="https://user-images.githubusercontent.com/41822696/177578040-30330005-0b5f-4972-87ff-a81efe385315.png">

**Comment by klizhentas** [comment]
@Alqanar header with white background with extra line, where we specify scope looks great, let's try this one

**Comment by klizhentas** [comment]
@Alqanar re: icons, let's try those, but move the icons in front of the text
